Repository Scents-Note/A.fume.Server, pull requests merged in 2020-11, with the labels that each got.

#6 Swagger-generated Project structure
  .gitignore
  .swagger-codegen-ignore
  .swagger-codegen/VERSION
  README.md
  api/swagger.yaml
  app.js
  bin/www
  controllers/Brand.js
  controllers/Ingredient.js
  controllers/Perfume.js
  controllers/Review.js
  controllers/Series.js
  controllers/User.js
  controllers/Wishlist.js
  dao/BrandDao.js
  index.js
  package.json
  public/stylesheets/style.css
  service/BrandService.js
  service/IngredientService.js
  service/PerfumeService.js
  service/ReviewService.js
  service/SeriesService.js
  service/UserService.js
  service/WishlistService.js
  src/app/controllers/controller.js
  src/app/dao/sampleDao.js
  src/app/routes.js
  src/app/services/sampleService.js
  test/app/dao/sampleDao.spec.js
  test/app/services/sampleService.spec.js
  test/dao/BrandDao.spec.js
  utils/db/pool.js
  utils/errors/errors.js
  utils/statusCode.js
  utils/writer.js
  views/error.jade
  views/index.jade
  views/layout.jade
Labels: SERVER, enhancement, 설계, 희성

#9 hee.youn
  dao/BrandDao.js
  dao/PerfumeDao.js
  dao/WishlistDao.js
  test/dao/BrandDao.spec.js
  test/dao/PerfumeDao.spec.js
  test/dao/WishlistDao.spec.js
  utils/db/pool.js
Labels: P1, SERVER, 희성

#22 [Swagger] reply
  api/swagger.yaml
Labels: P1, SERVER, 하담

#23 Node 버전 호환성 해결
  controllers/Reply.js
  package.json
  service/ReplyService.js
  test/dao/PerfumeDao.spec.js
Labels: P1, SERVER, 하담

#32 review Dao 구현 및 테스트
  dao/ReviewDao.js
  test/dao/ReviewDao.spec.js
Labels: P1, SERVER, enhancement, 하담

#30 jwt 모듈 구현
  lib/token.js
  package.json
  test/lib/token.spec.js
  utils/errors/errors.js
Labels: P2, SERVER, enhancement, 희성

#33 review 스웨거 작성
  api/swagger.yaml
  dao/ReplyDao.js
  dao/ReviewDao.js
Labels: P1, SERVER, enhancement, 하담
