Repository Scents-Note/A.fume.Server, pull requests merged in 2021-08, with the labels that each got.

#131 Feature/issue 130 seperate model
  controllers/Brand.js
  controllers/Series.js
  dao/BrandDao.js
  dao/SeriesDao.js
  data/dto/BrandDTO.js
  data/dto/BrandInputDTO.js
  data/dto/CreatedResultDTO.js
  data/dto/IngredientDTO.js
  data/dto/ListAndCountDTO.js
  data/dto/SeriesDTO.js
  data/dto/SeriesInputDTO.js
  data/dto/index.js
  data/request_dto/PagingRequestDTO.js
  data/request_dto/index.js
  data/response_dto/brand/BrandDetailResponseDTO.js
  data/response_dto/brand/BrandFilterResponseDTO.js
  data/response_dto/brand/BrandResponseDTO.js
  data/response_dto/brand/index.js
  data/response_dto/common/ListAndCountResponseDTO.js
  data/response_dto/common/ResponseDTO.js
  data/response_dto/common/index.js
  data/response_dto/ingredient/IngredientResponseDTO.js
  data/response_dto/ingredient/index.js
  data/response_dto/series/SeriesDetailResponseDTO.js
  data/response_dto/series/SeriesFilterResponseDTO.js
  data/response_dto/series/SeriesResponseDTO.js
  data/response_dto/series/index.js
  data/vo/BrandFilterVO.js
  data/vo/PagingVO.js
  data/vo/SeriesFilterVO.js
  data/vo/index.js
  index.js
  package.json
  service/BrandService.js
  service/SeriesService.js
  test/controller/Brand.spec.js
  test/controller/Series.spec.js
  test/dao/BrandDao.spec.js
  test/dao/SeriesDao.spec.js
  test/service/BrandService.spec.js
  test/service/SeriesService.spec.js
Labels: 리팩토링

#135 Feature/issue 134 user dto
  controllers/User.js
  dao/UserDao.js
  data/dto/LoginInfoDTO.js
  data/dto/SurveyDTO.js
  data/dto/TokenGroupDTO.js
  data/dto/TokenPayloadDTO.js
  data/dto/UserAuthDTO.js
  data/dto/UserDTO.js
  data/request_dto/UserInputRequestDTO.js
  data/response_dto/user/UserResponseDTO.js
  data/response_dto/user/index.js
  lib/token.js
  service/UserService.js
  test/controller/User.spec.js
  test/dao/BrandDao.spec.js
  test/dao/SeriesDao.spec.js
  test/dao/UserDao.mock.js
  test/dao/UserDao.spec.js
  test/data/dto/CreatedResultDTO.js
  test/data/dto/LoginInfoDTO.js
  test/data/dto/TokenGroupDTO.js
  test/data/dto/TokenPayloadDTO.js
  test/data/dto/UserAuthDTO.spec.js
  test/data/dto/UserDTO.js
  test/lib/crypto.mock.js
  test/lib/token.mock.js
  test/lib/token.spec.js
  test/service/UserService.mock.js
  test/service/UserService.spec.js
  utils/errors/errors.js
Labels: 리팩토링

#137 Ingredient find API 수정
  controllers/Ingredient.js
  dao/IngredientDao.js
  data/dto/IngredientConditionDTO.js
  service/IngredientService.js
  test/dao/IngredientDao.spec.js
Labels: bug

#139 remove unused api on swagger.yaml and controller
  api/swagger.yaml
  controllers/Ingredient.js
  controllers/Note.js
  controllers/Perfume.js
  controllers/Reply.js
  test/controller/Brand.spec.js
  test/controller/Series.spec.js
  test/controller/User.spec.js
Labels: 리팩토링

#144 Settings/issue 134 apply cross-env
  package-lock.json
  package.json
Labels: enhancement, SERVER

#146 Refactoring/issue 145 read by perfume idx
  dao/IngredientDao.js
  dao/NoteDao.js
  data/dto/NoteDTO.js
  models/note.js
  models/perfumeDefaultReview.js
  service/PerfumeService.js
  test/dao/IngredientDao.spec.js
  test/dao/NoteDao.spec.js
  test/dao/PerfumeDao.spec.js
  test/dao/UserDao.spec.js
  test/data/dto/NoteDTO.js
  test/service/PerfumeService.spec.js
  utils/code.js
  utils/constantUtil.js
Labels: enhancement

#142 Hotfix/test
  .github/workflows/node.js.yml
  dao/BrandDao.js
  dao/LikePerfumeDao.js
  dao/PerfumeDao.js
  lib/token.js
  service/PerfumeService.js
  test/controller/Brand.spec.js
  test/controller/Series.spec.js
  test/controller/User.spec.js
  test/dao/BrandDao.spec.js
  test/dao/IngredientDao.spec.js
  test/dao/KeywordDao.spec.js
  test/dao/LikePerfumeDao.spec.js
  test/dao/LikeReviewDao.spec.js
  test/dao/ReviewDao.spec.js
  test/dao/SeriesDao.spec.js
  test/dao/UserDao.spec.js
  test/dao/common/presets.js
  test/dao/common/seeds.js
  test/data/dto/BrandDTO.js
  test/data/dto/CreatedResultDTO.js
  test/data/dto/IngredientDTO.js
  test/data/dto/ListAndCountDTO.js
  test/data/dto/NoteDTO.js
  test/data/dto/SeriesDTO.js
  test/data/vo/BrandFilterVO.js
  test/data/vo/SeriesFilterVO.js
  test/lib/token.spec.js
  test/service/BrandService.spec.js
  test/service/SeriesService.spec.js
  test/service/UserService.spec.js
  test/utils/converter.spec.js
Labels: bug
