Repository Scents-Note/A.fume.Server, pull requests merged in 2021-07, with the labels that each got.

#123 Feature/supplement test case
  dao/BrandDao.js
  dao/IngredientDao.js
  dao/NoteDao.js
  dao/PerfumeDao.js
  dao/SearchHistoryDao.js
  dao/SeriesDao.js
  dao/UserDao.js
  models/perfumeSurvey.js
  models/searchHistory.js
  service/PerfumeService.js
  test/dao/BrandDao.spec.js
  test/dao/IngredientDao.spec.js
  test/dao/KeywordDao.spec.js
  test/dao/LikePerfumeDao.spec.js
  test/dao/LikeReviewDao.spec.js
  test/dao/NoteDao.spec.js
  test/dao/PerfumeDao.spec.js
  test/dao/ReviewDao.spec.js
  test/dao/SearchHistoryDao.spec.js
  test/dao/SeriesDao.spec.js
  test/dao/UserDao.spec.js
  test/dao/common/seeds.js
  utils/errors/errors.js
Labels: SERVER

#124 converter 모듈 추가
  dao/KeywordDao.js
  test/utils/converter.spec.js
  utils/converter.js
  utils/errors/errors.js
Labels: SERVER, enhancement, 하담

#127 Feature/issue 125
  dao/NoteDao.js
  models/ingredient.js
  models/perfumeSurvey.js
  service/BrandService.js
  service/PerfumeService.js
  service/SeriesService.js
  test/dao/NoteDao.spec.js
Labels: enhancement, 희성

#129 [feat] Add Review Feature
  api/swagger.yaml
  controllers/Review.js
  dao/LikeReviewDao.js
  dao/ReviewDao.js
  service/ReviewService.js
  utils/converter.js
Labels: SERVER, enhancement
