Repository Scents-Note/A.fume.Server, pull requests merged in 2022-12, with the labels that each got.

#420 Bug/issue 381 missing private review
  src/dao/ReviewDao.ts
  src/service/PerfumeService.ts
  tests/test_unit/dao/PerfumeDao.spec.ts
  tests/test_unit/dao/ReviewDao.spec.js
  tests/test_unit/dao/common/seeds.js
Labels: bug

#417 [Feat] 비슷한 향수 추천 데이터 DB 반영 API 구현
  .github/workflows/exec-mocha-integral-test.yml
  .github/workflows/exec-mocha-unit-test.yml
  package-lock.json
  package.json
  src/controllers/Perfume.ts
  src/dao/PerfumeDao.ts
  src/service/PerfumeService.ts
  src/utils/db/redis.js
  src/utils/properties.ts
  src/utils/strings.ts
Labels: enhancement, fix

#430 Create pull_request_template.md
  .github/pull_request_template.md
Labels: documentation

#431 Modify app.ts to parse large JSON format body data
  package-lock.json
  package.json
  src/app.ts
Labels: bug

#434 Update deploy-development.yml
  .github/workflows/deploy-development.yml
Labels: bug

#436 Bug/issue 435 nodejs 12 actions are deprecated
  .github/workflows/deploy-development.yml
Labels: bug

#437 Bug/issue 435 nodejs 12 actions are deprecated
  .github/workflows/deploy-development.yml
Labels: bug

#442 [Fix] Update package files
  package-lock.json
  package.json
Labels: bug

#443 Bug/issue 441 high severity vulnerabilities was found
  .github/workflows/deploy-development.yml
  package-lock.json
  package.json
Labels: bug
